---
- hosts: windows
- name: test raw module
  hosts: all
  tasks:
    - name: run ipconfig
      raw: ipconfig
      register: ipconfig
    - debug: var=ipconfig

# - name: test stat module
#   hosts: windows
#   tasks:
#     - name: test stat module on file
#       win_stat: path="C:/Windows/win.ini"
#       register: stat_file
#
#     - debug: var=stat_file
#
#     - name: check stat_file result
#       assert:
#           that:
#              - "stat_file.stat.exists"
#              - "not stat_file.stat.isdir"
#              - "stat_file.stat.size > 0"
#              - "stat_file.stat.md5"

# see https://docs.ansible.com/ansible/2.5/modules/win_file_module.html#win-file-module
- name: Touch a file (creates if not present, updates modification time if present)
  hosts: windows
  tasks:
    - name: Create a file
      win_file:
        path: C:\tmp\foo.conf
        #path: C:\Program Files\test-jc.txt
        state: touch

# downlaod a file: see https://docs.ansible.com/ansible/2.5/modules/win_get_url_module.html
- name: Download earthrise.jpg to specified path only if modified
  hosts: windows
  tasks:
  - name: Download a file
    win_get_url:
      url: https://unsplash.com/photos/IIs48GYoEww/download
      dest: C:\tmp\jasonstmpfolder\earthrise.jpg
      force: no

# install Chocolatey package manager and Git
# see https://docs.ansible.com/ansible/2.5/modules/win_chocolatey_module.html
- name: Install Chocolatey and Git
  hosts: windows
  tasks:
  - name: Choc and Git install
    win_chocolatey:
      name: poshgit
      state: present

# install google chrome
# see https://docs.ansible.com/ansible/2.5/modules/win_chocolatey_module.html
- name: Install Chrome
  hosts: windows
  tasks:
  - name: Install Chrome
    win_chocolatey:
      name: googlechrome
      state: present

# clone katalon repo
# - name: Clone katalon repo
#   hosts: windows
#   tasks:
#   - name: git clone katalon
#     win_git:
#       repo: http://git.healthcog.org/jcarney/katalon-testing.git
#       dest: C:\tmp\jasonstmpfolder\Ansible-win_git
#       branch: object_repo_changes_2018_04_20
#       update: no
#       replace_dest: no
#       accept_hostkey: yes

# try to change into the git folder
# - name: try to change into the git folder
#   hosts: windows
#   tasks:
#   - name: try to change into the git folder
#     raw: cd 'C:\Program Files\Git'

# see https://stackoverflow.com/questions/39301265/how-to-clone-git-repository-using-ansible-under-microsoft-windows
- name: Clone katalon repo
  hosts: windows
  tasks:
  - name: Clone katalon repo
    raw: C:\Program Files\Git\git-bash.exe clone http://git.healthcog.org/jcarney/katalon-testing.git C:\tmp\jasonstmpfolder\Ansible-win_git
