###############################################################
# // ph config
###############################################################

## ------------------------------------- ##
## ph directories and permissions ##
## ------------------------------------- ##

- name: Configure /etc/ph
  tags: configureph
  file:
    path: /etc/ph
    state: directory
    owner: "{{ph_owner}}"
    group: "{{ph_group}}"
    mode: 0755

- name: Configure /etc/ph/ldap
  tags: configureph
  file:
    path: /etc/ph/ldap
    state: directory
    owner: "{{ph_owner}}"
    group: "{{ph_group}}"
    mode: 0755

- name: Configure /etc/ph/conf
  tags: configureph
  file:
    path: /etc/ph/conf
    state: directory
    owner: "{{ph_owner}}"
    group: "{{ph_group}}"
    mode: 0755
    
- name: Copy across local ph-logging.groovy to /etc/ph/conf/ph-logging.groovy
  tags: configureph
  template:
    src: /vagrant-shared/config/phconfig/ph-logging.groovy
    dest: /etc/ph/conf/ph-logging.groovy
    owner: "{{ph_owner}}"
    group: "{{ph_group}}"

- name: Copy ph config, setting passwords as we go
  tags: configureph, test
  template:
    src: /vagrant-shared/config/phconfig/Config.groovy.template
    dest: /etc/ph/conf/Config.groovy
    owner: "{{ph_owner}}"
    group: "{{ph_group}}"

- name: Configure ph Create pumphouse and fixures folder at /var/lib
  tags: configureph
  file:
    path: /var/lib/ph/fixtures
    state: directory
    owner: "{{ph_owner}}"
    group: "{{ph_group}}"
    mode: 0755

- name: check for existance of /var/lib/ph/fixtures/core 
  tags: configureph
  stat: 
    path: /var/lib/ph/fixtures/core 
  register: fixtures_core

- name: Configure ph /var/lib/fixtures/core
  tags: configureph
  file:
    path: /var/lib/ph/fixtures/core
    state: directory
    owner: "{{ph_owner}}"
    group: "{{ph_group}}"
    mode: 0755
  when: fixtures_core.stat.exists == False
    

- name: Configure ph /var/lib/fixtures/project1
  tags: configureph
  file:
    path: /var/lib/ph/fixtures/project1
    state: directory
    owner: "{{ph_owner}}"
    group: "{{ph_group}}"
    mode: 0755

- name: Configure ph /var/lib/fixtures/project2
  tags: configureph
  file:
    path: /var/lib/ph/fixtures/project2
    state: directory
    owner: "{{ph_owner}}"
    group: "{{ph_group}}"
    mode: 0755

- name: Configure ph /var/lib/fixtures/project3
  tags: configureph
  file:
    path: /var/lib/ph/fixtures/project3
    state: directory
    owner: "{{ph_owner}}"
    group: "{{ph_group}}"
    mode: 0755

- name: Configure ph Create uploads folder at /var/lib/ph
  tags: configureph
  file:
    path: /var/lib/ph/uploads
    state: directory
    owner: "{{ph_owner}}"
    group: "{{ph_group}}"
    mode: 0755

- name: Configure ph Create melody log folder at /var/log/melody
  tags: configureph
  file:
    path: /var/log/melody
    state: directory
    owner: "{{ph_owner}}"
    group: "{{ph_group}}"


# if we are not doing PH dev, then we are running PH from tomcat, and thus will need to increase memory & configure logging
- name: Tomcat java opts
  tags: configureph
  when: vm_type != "ph_dev"
  lineinfile:
    path: /etc/default/tomcat8
    regexp: '^JAVA_OPTS='
    line: 'JAVA_OPTS="-Djava.awt.headless=true -XX:+CMSClassUnloadingEnabled -XX:+UseConcMarkSweepGC -server -Xms1024M -Xmx2048M -XX:MaxMetaspaceSize=1G -Dlogging.config=/etc/ph/conf/ph-logging.groovy  -Dcom.sun.management.jmxremote=true -Dcom.sun.management.jmxremote.local.only=false -Dcom.sun.management.jmxremote.password.file=/etc/ph/conf/jmxremote.password -Dcom.sun.management.jmxremote.access.file=/etc/ph/conf/jmxremote.access -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.port=8123 -Djava.rmi.server.hostname={{host_name}} -Dcom.sun.management.jmxremote.rmi.port=8124"'
    state: present
    
- name: Tomcat jmx access file
  tags: configureph
  when: vm_type != "ph_dev"
  template:
    src: /vagrant-shared/config/phconfig/jmxremote.access.template
    dest: /etc/ph/conf/jmxremote.access
    owner: "{{ph_owner}}"
    group: "{{ph_group}}"
    
- name: Tomcat jmx password file
  tags: configureph
  when: vm_type != "ph_dev"
  template:
    src: /vagrant-shared/config/phconfig/jmxremote.password.template
    dest: /etc/ph/conf/jmxremote.password
    owner: "{{ph_owner}}"
    group: "{{ph_group}}"
    mode: 0600
    
- name: ph encryption key
  tags: configureph
  template:
    src: /vagrant-shared/config/phconfig/keyfile.template
    dest: /etc/ph/conf/keyfile
    owner: "{{ph_owner}}"
    group: "{{ph_group}}"
    mode: 0600    
            
    
