###############################################################
# // Clone previous ph configuration via git
###############################################################

- name: Clone previous ph configuration
  tags: cloneph
  git: repo="http://{{ git_user }}:{{ git_password }}@{{platform_repo}}" dest="/{{ansible_ph}}/{{ansible_ph_config}}"
